site_name: BFWiki
site_url: http://localhost:8080/BFWiki
repo_url: https://github.com/bearfly1990/BF-Wiki/tree/gh-pages
site_author: bearfly1990
site_description: wiki for bearfly1990
# copyright:
# nav:
#     - Home: index.md
#     - About: about.md
#     - Kafka:
#       - Learn Note01: 2021/08/2021-08-09-kafka-learn-01.md
# pages:
# - [index.md, Home]
# - [about.md, About]
theme:
    # name: readthedocs
    name: material
    language: 'zh'
    # logo: img/xxx.ico
    favicon: assets/img/favicon.ico
    primary: "Blue Grey"
    # accent: "Pink"
    font:
        text: Incosolata
        # code: Consolas
        # text: Courier New
        # text: Calibri
    features:
        # - tabs: true
        # - toc.integrate
        # - navigation.tracking
        - content.code.annotate # (1)
        - navigation.tabs
        - navigation.top
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    # nav_style: dark
    # icon:
    #     admonition:
    #         <type>: <icon> # (1)!
plugins:
    - tags
        # tags_file: tags.md
    - search
    - exclude:
        glob:
            # - exclude/this/path/*
            - "*.tmp"
            # - "*.pdf"
            - "*.gz"
        regex:
            - '.*\.(tmp|bin|tar)$'

# extra:
#     search:
#         language: 'zh'

markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - md_in_html
    - codehilite:
          guess_lang: false
          linenums: false
    - toc:
          permalink: "#"
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        # emoji_generator: !!python/name:pymdownx.emoji.to_png
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.tilde
    - pymdownx.highlight:
        anchor_linenums: true

extra_css:
  - assets/static/extra.css
# site_name: JetBot
# theme:
#     name: "material"
#     logo: images/logo.png
#     favicon: images/favicon.png
#     font: Incosolata
#     palette:
#         scheme: nvgreen
#     features:
#        - navigation.expand
#
# repo_url: https://github.com/NVIDIA-AI-IOT/jetbot
#
plugins:
    - search
    - exclude:
        regex:
            - '.*~.*\.(xlsx)$'
# use_directory_urls: false
#
# edit_uri: blob/master/docs
# markdown_extensions:
#   - pymdownx.tabbed
#   - pymdownx.keys
#   - pymdownx.snippets
#   - pymdownx.inlinehilite
#   - pymdownx.highlight:
#         use_pygments: true
#   - admonition
#   - pymdownx.details
#   - pymdownx.superfences
#   - attr_list  # for image sizes https://github.com/mkdocs/mkdocs/issues/1678
# # use_directory_urls - False to fix broken raw html image links
# # https://github.com/mkdocs/mkdocs/issues/991
#
#
# nav:
#
#   - Home: index.md
#   - Getting Started: getting_started.md
#   - Bill of Materials: bill_of_materials.md
#   - Hardware Setup: hardware_setup.md
#   - Software Setup:
#       - Using SD Card Image: software_setup/sd_card.md
#       - Using Docker Container: software_setup/docker.md
#   - Examples:
#       - Basic Motion: examples/basic_motion.md
#       - Teleoperation: examples/teleoperation.md
#       - Collision Avoidance: examples/collision_avoidance.md
#       - Road Following: examples/road_following.md
#       - Object Following: examples/object_following.md
#   - Reference:
#       - Third Party Kits: third_party_kits.md
#       - 3D Printing: 3d_printing.md
#       - Contributing: CONTRIBUTING.md
#       - Changes: CHANGELOG.md
#       - Wi-Fi setup: software_setup/wifi_setup.md
#       - Docker Tips: reference/docker_tips.md
#
extra_css:
  - assets/static/my.css
extra_javascript:
  - assets/static/my.js

# google_analytics:
#   - UA-135919510-2
#   - auto
